import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import test from "node:test";

test("generated bindings have a deterministic warning header", async () => {
  const bindings = await readFile("src/generated/bindings.ts", "utf8");
  assert.ok(bindings.startsWith("// Generated by ts-rs. Do not edit.\n"));
  assert.match(bindings, /export type CommandResult<T>/);
  assert.match(bindings, /export type FoundationStatus/);
  assert.match(bindings, /export type PublicError/);
});

test("only the command adapter imports the low-level Tauri invoke API", () => {
  const output = execFileSync(
    "rg",
    ["-l", "@tauri-apps/api/core", "src", "--glob", "*.ts", "--glob", "*.tsx"],
    { encoding: "utf8" },
  );
  const files = output.trim().split(/\r?\n/).map((file) => file.replaceAll("\\", "/"));
  assert.deepEqual(files, ["src/api/commands.ts"]);
});
