#[cfg(test)]
use std::path::Path;

use serde::{Serialize, Serializer, ser::SerializeMap};
use ts_rs::TS;

pub use crate::error::PublicError;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct FoundationStatus {
    pub ready: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct SecretStatus {
    pub reference: String,
    pub configured: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, TS)]
#[ts(type = "{ ok: true; data: T } | { ok: false; error: PublicError }")]
pub enum CommandResult<T: TS> {
    Ok { data: T },
    Err { error: PublicError },
}

impl<T: Serialize + TS> Serialize for CommandResult<T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut map = serializer.serialize_map(Some(2))?;
        match self {
            Self::Ok { data } => {
                map.serialize_entry("ok", &true)?;
                map.serialize_entry("data", data)?;
            }
            Self::Err { error } => {
                map.serialize_entry("ok", &false)?;
                map.serialize_entry("error", error)?;
            }
        }
        map.end()
    }
}

#[cfg(test)]
fn generated_bindings() -> String {
    let config = ts_rs::Config::default();
    format!(
        "// Generated by ts-rs. Do not edit.\n\nexport {}\n\nexport {}\n\nexport {}\n\nexport {}\n",
        PublicError::decl(&config),
        FoundationStatus::decl(&config),
        SecretStatus::decl(&config),
        CommandResult::<FoundationStatus>::decl(&config),
    )
}

#[cfg(test)]
fn write_bindings(path: &Path) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create generated binding directory");
    }
    std::fs::write(path, generated_bindings()).expect("write generated TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::{
        CommandResult, FoundationStatus, PublicError, SecretStatus, generated_bindings,
        write_bindings,
    };
    use serde_json::json;
    use std::path::Path;

    #[test]
    fn contracts_serialize_with_stable_shapes() {
        assert_eq!(
            serde_json::to_value(CommandResult::Ok {
                data: FoundationStatus { ready: true },
            })
            .unwrap(),
            json!({"ok": true, "data": {"ready": true}})
        );
        assert_eq!(
            serde_json::to_value(CommandResult::<FoundationStatus>::Err {
                error: PublicError::new("CONFIG_INVALID", "配置无效", false)
                    .with_field("providers"),
            })
            .unwrap()["ok"],
            false
        );
        assert_eq!(
            PublicError::new("CONFIG_INVALID", "配置无效", false).code,
            "CONFIG_INVALID"
        );
    }

    #[test]
    fn export_bindings() {
        let bindings = generated_bindings();
        assert!(
            bindings.contains("export type CommandResult<T>"),
            "unexpected bindings:\n{bindings}"
        );
        assert!(bindings.contains("ok: true"));
        assert!(bindings.contains("ok: false"));
        assert!(bindings.contains("export type SecretStatus"));
        write_bindings(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/generated/bindings.ts"));
    }
}
