#[cfg(test)]
use std::path::Path;

#[cfg(test)]
use crate::config::{
    ApplicationConfig, DiagnosticsConfig, EmbeddingConfig, EmbeddingDistance, KnowledgeConfig,
    LiveKitConfig, ModelConfig, ProviderConfig, PublicConfig, RoleProfileConfig, SecretSlot,
    SpeechConfig, StorageConfig, TransportConfig, VoiceRouteConfig, VoiceRouteMode,
};
#[cfg(test)]
use crate::services::{
    DiscoveredModelDto, EmbeddingConfigSaveInput, EmbeddingTestResult, LiveKitSettingsSaveInput,
    LiveKitTestResult, ModelDiscoveryResult, ProviderSaveInput, ProviderTestResult,
    RoleProfileCopyInput, RoleProfileSaveInput, VoiceRouteSaveInput, VoiceRouteTestResult,
};

use serde::{Serialize, Serializer, ser::SerializeMap};
use ts_rs::TS;

pub use crate::error::PublicError;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct FoundationStatus {
    pub ready: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct SecretStatus {
    pub reference: String,
    pub configured: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct DiagnosticsExportResult {
    pub exported: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, TS)]
#[serde(tag = "kind", rename_all = "camelCase")]
#[ts(tag = "kind", rename_all = "camelCase")]
pub enum StartupState {
    Ready,
    Migrated,
    Recoverable { error: PublicError },
    Invalid { error: PublicError },
}

#[derive(Debug, Clone, PartialEq, Eq, TS)]
#[ts(type = "{ ok: true; data: T } | { ok: false; error: PublicError }")]
pub enum CommandResult<T: TS> {
    Ok { data: T },
    Err { error: PublicError },
}

impl<T: Serialize + TS> Serialize for CommandResult<T> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut map = serializer.serialize_map(Some(2))?;
        match self {
            Self::Ok { data } => {
                map.serialize_entry("ok", &true)?;
                map.serialize_entry("data", data)?;
            }
            Self::Err { error } => {
                map.serialize_entry("ok", &false)?;
                map.serialize_entry("error", error)?;
            }
        }
        map.end()
    }
}

#[cfg(test)]
fn generated_bindings() -> String {
    let config = ts_rs::Config::default();
    // Registry of public DTO declarations. Emit order == registry order; adding a
    // new DTO to the public contract only requires adding one more `decl` entry.
    let decls = [
        PublicError::decl(&config),
        FoundationStatus::decl(&config),
        SecretStatus::decl(&config),
        DiagnosticsExportResult::decl(&config),
        StartupState::decl(&config),
        // Config contract DTOs (Phase 3 Stage B): the redacted public
        // configuration tree. Providers only carry SecretSlot references; no
        // secret value is ever part of this contract.
        SecretSlot::decl(&config),
        ApplicationConfig::decl(&config),
        ProviderConfig::decl(&config),
        ModelConfig::decl(&config),
        VoiceRouteMode::decl(&config),
        VoiceRouteConfig::decl(&config),
        SpeechConfig::decl(&config),
        LiveKitConfig::decl(&config),
        TransportConfig::decl(&config),
        EmbeddingDistance::decl(&config),
        EmbeddingConfig::decl(&config),
        KnowledgeConfig::decl(&config),
        StorageConfig::decl(&config),
        RoleProfileConfig::decl(&config),
        DiagnosticsConfig::decl(&config),
        PublicConfig::decl(&config),
        ProviderSaveInput::decl(&config),
        ProviderTestResult::decl(&config),
        DiscoveredModelDto::decl(&config),
        ModelDiscoveryResult::decl(&config),
        VoiceRouteSaveInput::decl(&config),
        VoiceRouteTestResult::decl(&config),
        RoleProfileSaveInput::decl(&config),
        RoleProfileCopyInput::decl(&config),
        EmbeddingConfigSaveInput::decl(&config),
        EmbeddingTestResult::decl(&config),
        LiveKitSettingsSaveInput::decl(&config),
        LiveKitTestResult::decl(&config),
        CommandResult::<FoundationStatus>::decl(&config),
    ];
    let header = "// Generated by ts-rs. Do not edit.\n";
    let body = decls
        .iter()
        .map(|decl| format!("export {decl}\n"))
        .collect::<Vec<String>>()
        .join("\n");
    format!("{header}\n{body}")
}

#[cfg(test)]
fn write_bindings(path: &Path) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create generated binding directory");
    }
    std::fs::write(path, generated_bindings()).expect("write generated TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::{CommandResult, FoundationStatus, PublicError, generated_bindings, write_bindings};
    use serde_json::json;
    use std::path::Path;

    #[test]
    fn contracts_serialize_with_stable_shapes() {
        assert_eq!(
            serde_json::to_value(CommandResult::Ok {
                data: FoundationStatus { ready: true },
            })
            .unwrap(),
            json!({"ok": true, "data": {"ready": true}})
        );
        assert_eq!(
            serde_json::to_value(CommandResult::<FoundationStatus>::Err {
                error: PublicError::new("CONFIG_INVALID", "配置无效", false)
                    .with_field("providers"),
            })
            .unwrap()["ok"],
            false
        );
        assert_eq!(
            PublicError::new("CONFIG_INVALID", "配置无效", false).code,
            "CONFIG_INVALID"
        );
    }

    #[test]
    fn export_bindings() {
        let bindings = generated_bindings();
        assert!(
            bindings.contains("export type CommandResult<T>"),
            "unexpected bindings:\n{bindings}"
        );
        assert!(bindings.contains("ok: true"));
        assert!(bindings.contains("ok: false"));
        assert!(bindings.contains("export type SecretStatus"));
        assert!(bindings.contains("export type DiagnosticsExportResult"));
        assert!(bindings.contains("export type StartupState"));
        assert!(bindings.contains("export type PublicConfig"));
        assert!(bindings.contains("export type VoiceRouteMode"));
        assert!(bindings.contains("export type VoiceRouteConfig"));
        assert!(bindings.contains("export type RoleProfileConfig"));
        assert!(bindings.contains("export type EmbeddingConfig"));
        assert!(bindings.contains("export type LiveKitConfig"));
        assert!(bindings.contains("export type RoleProfileSaveInput"));
        assert!(bindings.contains("export type EmbeddingConfigSaveInput"));
        assert!(bindings.contains("export type LiveKitSettingsSaveInput"));
        write_bindings(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/generated/bindings.ts"));
    }
}
